name: do-the-thing
on: [push]
jobs:
  test:
    strategy:
      matrix:
        # TODO https://github.com/lun-4/awtfdb/issues/1
        # TODO https://github.com/lun-4/awtfdb/issues/2
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-22.04]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v1.3.0
        with:
          version: 0.11.0-dev.1390+74b72a766
      - run: curl -L -w "%{http_code}" -o /usr/local/bin/zigmod https://github.com/nektro/zigmod/releases/download/r83/zigmod-x86_64-linux
      - run: chmod +x /usr/local/bin/zigmod
      - run: zigmod ci
      - run: sudo apt install -y libmagic1 graphicsmagick-dev
      - run: zig build test
      - run: ci/smoketest.sh
