name: do-the-thing
on: [push]
jobs:
  test:
    strategy:
      matrix:
        # TODO https://github.com/lun-4/awtfdb/issues/1
        # TODO https://github.com/lun-4/awtfdb/issues/2
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v1.3.0
        with:
          version: 0.10.0-dev.1902+42ed34d1f
      - run: curl -L -w "%{http_code}" -o /usr/local/bin/zigmod https://github.com/nektro/zigmod/releases/download/r77/zigmod-x86_64-linux
      - run: zigmod ci
      - run: zig build test
